backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Page d'accueil"
        name: "accueil"
        fields:
          - {label: "Titre de la page", name: "title", widget: "string"}
